version: "3"
services: 
  todotests:
    image: todotests
    restart: unless-stopped
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback

  todofront:
    image: todofrontend
    restart: unless-stopped
    ports: 
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback

  todoback: 
    image: todobackend
    restart: unless-stopped
    ports: 
      - 3001:3001

